version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: inventory_frontend
    ports:
      - "5173:5173"
    depends_on: 
      - backend
    stdin_open: true
    tty: true
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - WDS_SOCKET_PORT=0  # Fix React Fast Refresh inside Docker

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: inventory_backend
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    env_file:
      - backend/.env
    restart: always  # Ensures the container restarts if it fails
    volumes:
      - ./backend:/app
      - /app/node_modules

  mongo:
    image: mongo:latest
    container_name: inventory_mongodb
    restart: always  # Ensures MongoDB keeps running
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: sujal
      MONGO_INITDB_ROOT_PASSWORD: sujal123
    volumes:
      - mongodb_data:/data/db  # Ensures data persists after container restarts

volumes:
  mongodb_data:
